# Generated by Django 5.1.7 on 2025-03-30 21:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logical_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('REST', 'REST'), ('SOAP', 'SOAP')], default='REST', max_length=20)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'type'), name='unique_name_type')],
            },
        ),
    ]
