# Generated by Django 5.1.7 on 2025-03-31 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_alter_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
