# Generated by Django 5.1.7 on 2025-04-01 18:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logical_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('uri', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='unique_project_name'),
        ),
        migrations.AddField(
            model_name='resource',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.application'),
        ),
        migrations.AddConstraint(
            model_name='resource',
            constraint=models.UniqueConstraint(fields=('application', 'name'), name='unique_application_name'),
        ),
    ]
